name: example

# ----------------------------------------------------------------------------------------------------------------------
#
# Детально, но изолированно, контейнеры приложений описаны в соответствующих файлах.
# Например, docker-compose._app_monitoring.yml.
#
# В этом файле все контейнеры приложений объединяются в единую готовую к эксплуатации систему.
#
# depends_on приводят к каскадному перестроению множества сервисов при изменении зависимого, что чаще не требуется.
# Кроме того, depends_on создает последовательные цепочки запуска, что ощутимо замедляет старт проекта.
# ----------------------------------------------------------------------------------------------------------------------

networks:
  admin-front-network:            # `front` --> `gateway`
  admin-internal-network:         # `gateway` --> ...внутренние-сервисы... <--> ...внутренние-сервисы ...
  infrastructure-kafka-network:   # `infrastructure-kafka-...` между собой и миграциями
  infrastructure-mysql-network:   # `infrastructure-mysql-prometheus-exporter` и миграции --> `infrastructure-...`
  infrastructure-redis-network:   # `infrastructure-redis-prometheus-exporter` и миграции --> `infrastructure-...`
  monitoring-internal-network:    # ...внутренние-сервисы... <--> ...внутренние-сервисы ...
  monitoring-logs-network:        # все экспортеры --> loki
  monitoring-metrics-network:     # все экспортеры --> prometheus (см. monitoring/build/prometheus/prometheus.yml).

services:
  # --------------------------------------------------------------------------------------------------------------------
  # ADMIN
  # --------------------------------------------------------------------------------------------------------------------

  # AUTH
  # --------------------------------------------------------------------------------------------------------------------

  admin-auth-grpc:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-auth-grpc
    networks:
      - admin-internal-network
      - monitoring-metrics-network

  admin-auth-sch:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-auth-sch
    networks:
      - admin-internal-network
      - monitoring-metrics-network

  admin-auth-logs-exporter:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-auth-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  # CFM
  # --------------------------------------------------------------------------------------------------------------------

  admin-cfm-grpc:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-cfm-grpc
    networks:
      - admin-internal-network
      - monitoring-metrics-network

  admin-cfm-sch:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-cfm-sch
    networks:
      - admin-internal-network
      - monitoring-metrics-network

  admin-cfm-logs-exporter:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-cfm-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  # FRONT
  # --------------------------------------------------------------------------------------------------------------------

  admin-front-server:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-front-server
    networks:
      - admin-front-network
    ports:
      - ${DEPLOY_PUBLIC_PORT_ADMIN}:80

  # GATEWAY
  # --------------------------------------------------------------------------------------------------------------------

  admin-gateway-http:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-gateway-http
    networks:
      - admin-front-network
      - admin-internal-network
      - monitoring-metrics-network

  admin-gateway-logs-exporter:
    extends:
      file: docker-compose._app_admin.yml
      service: admin-gateway-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  # --------------------------------------------------------------------------------------------------------------------
  # INFRASTRUCTURE
  # --------------------------------------------------------------------------------------------------------------------

  # KAFKA
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-kafka-server-a:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-server-a
    networks:
      - infrastructure-kafka-network
      - admin-internal-network

  infrastructure-kafka-server-b:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-server-b
    networks:
      - infrastructure-kafka-network
      - admin-internal-network

  infrastructure-kafka-server-c:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-server-c
    networks:
      - infrastructure-kafka-network
      - admin-internal-network

  infrastructure-kafka-connect:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-connect
    networks:
      - infrastructure-mysql-network
      - infrastructure-kafka-network
      - monitoring-metrics-network

  infrastructure-kafka-logs-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  infrastructure-kafka-prometheus-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-kafka-prometheus-exporter
    networks:
      - infrastructure-kafka-network
      - monitoring-metrics-network

  # MYSQL
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-mysql-master:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-mysql-master
    networks:
      - infrastructure-mysql-network
      - admin-internal-network

  infrastructure-mysql-replica:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-mysql-replica
    networks:
      - infrastructure-mysql-network
      - admin-internal-network

  infrastructure-mysql-prometheus-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-mysql-prometheus-exporter
    networks:
      - infrastructure-mysql-network
      - monitoring-metrics-network

  infrastructure-mysql-logs-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-mysql-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  # REDIS
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-redis-cache:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-redis-cache
    networks:
      - infrastructure-redis-network
      - admin-internal-network

  infrastructure-redis-prometheus-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-redis-prometheus-exporter
    networks:
      - infrastructure-redis-network
      - monitoring-metrics-network

  infrastructure-redis-logs-exporter:
    extends:
      file: docker-compose._app_infrastructure.yml
      service: infrastructure-redis-logs-exporter
    build:
      args:
        LOKI_BASEURL: "http://monitoring-loki:3100"
    networks:
      - monitoring-logs-network

  # --------------------------------------------------------------------------------------------------------------------
  # MONITORING
  # --------------------------------------------------------------------------------------------------------------------

  monitoring-alertmanager:
    extends:
      file: docker-compose._app_monitoring.yml
      service: monitoring-alertmanager
    networks:
      - monitoring-internal-network

  monitoring-grafana:
    extends:
      file: docker-compose._app_monitoring.yml
      service: monitoring-grafana
    networks:
      - monitoring-internal-network
    ports:
      - ${DEPLOY_PUBLIC_PORT_MONITORING}:3000

  monitoring-loki:
    extends:
      file: docker-compose._app_monitoring.yml
      service: monitoring-loki
    networks:
      - monitoring-logs-network
      - monitoring-internal-network

  monitoring-prometheus:
    extends:
      file: docker-compose._app_monitoring.yml
      service: monitoring-prometheus
    networks:
      - monitoring-metrics-network
      - monitoring-internal-network

  # --------------------------------------------------------------------------------------------------------------------
  # NODE
  # --------------------------------------------------------------------------------------------------------------------

  node-logrotate:
    extends:
      file: docker-compose._app_node.yml
      service: node-logrotate

  node-prometheus-exporter-proxy:
    extends:
      file: docker-compose._app_node.yml
      service: node-prometheus-exporter-proxy
    networks:
      - monitoring-metrics-network

  node-prometheus-exporter-local-pusher:
    extends:
      file: docker-compose._app_node.yml
      service: node-prometheus-exporter-local-pusher
    network_mode: host # !!!

  node-prometheus-exporter-local-exporter:
    extends:
      file: docker-compose._app_node.yml
      service: node-prometheus-exporter-local-exporter
    network_mode: host # !!!

  # --------------------------------------------------------------------------------------------------------------------
