name: example

services:
  # --------------------------------------------------------------------------------------------------------------------
  # AUTH
  # --------------------------------------------------------------------------------------------------------------------

  admin-auth-grpc:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/auth
      dockerfile: build/grpc/Dockerfile
    environment:
      MYSQL_HOST_MASTER: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_HOST_REPLICA: ${INFRASTRUCTURE_MYSQL_HOST_REPLICA}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_PASSWORD}
      MYSQL_DB: ${INFRASTRUCTURE_MYSQL_DB_AUTH}
      API_GRPC_APIKEY: ${ADMIN_AUTH_API_GRPC_APIKEY}
      SERVICE_CFM_API_GRPC_BASEURL: "admin-cfm-grpc:50051"
      SERVICE_CFM_API_GRPC_APIKEY: ${ADMIN_CFM_API_GRPC_APIKEY}
    volumes:
      - ./admin/auth/state/grpc:/state
    develop:
      watch:
        - action: rebuild
          path: admin/auth/app
        - action: rebuild
          path: admin/auth/build/grpc

  # --------------------------------------------------------------------------------------------------------------------

  admin-auth-sch:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/auth
      dockerfile: build/sch/Dockerfile
    environment:
      MYSQL_HOST_MASTER: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_HOST_REPLICA: ${INFRASTRUCTURE_MYSQL_HOST_REPLICA}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_PASSWORD}
      MYSQL_DB: ${INFRASTRUCTURE_MYSQL_DB_AUTH}
    volumes:
      - ./admin/auth/state/sch:/state
    develop:
      watch:
        - action: rebuild
          path: admin/auth/app
        - action: rebuild
          path: admin/auth/build/sch

  # --------------------------------------------------------------------------------------------------------------------

  admin-auth-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/auth
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./admin/auth/state/logs-exporter:/state
      - ./admin/auth/state/grpc:/input/grpc
      - ./admin/auth/state/sch:/input/sch
    develop:
      watch:
        - action: rebuild
          path: admin/auth/build/logs-exporter

  # --------------------------------------------------------------------------------------------------------------------
  # CFM
  # --------------------------------------------------------------------------------------------------------------------

  admin-cfm-grpc:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/cfm
      dockerfile: build/grpc/Dockerfile
    environment:
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_PASSWORD}
      MYSQL_DB: ${INFRASTRUCTURE_MYSQL_DB_CFM}
      API_GRPC_APIKEY: ${ADMIN_CFM_API_GRPC_APIKEY}
    volumes:
      - ./admin/cfm/state/grpc:/state
    develop:
      watch:
        - action: rebuild
          path: admin/cfm/app
        - action: rebuild
          path: admin/cfm/build/grpc

  # --------------------------------------------------------------------------------------------------------------------

  admin-cfm-sch:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/cfm
      dockerfile: build/sch/Dockerfile
    environment:
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_PASSWORD}
      MYSQL_DB: ${INFRASTRUCTURE_MYSQL_DB_CFM}
      API_GRPC_APIKEY: ${ADMIN_CFM_API_GRPC_APIKEY}
    volumes:
      - ./admin/cfm/state/sch:/state
    develop:
      watch:
        - action: rebuild
          path: admin/cfm/app
        - action: rebuild
          path: admin/cfm/build/sch

  # --------------------------------------------------------------------------------------------------------------------

  admin-cfm-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/cfm
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./admin/cfm/state/logs-exporter:/state
      - ./admin/cfm/state/grpc:/input/grpc
      - ./admin/cfm/state/sch:/input/sch
    develop:
      watch:
        - action: rebuild
          path: admin/cfm/build/logs-exporter

  # --------------------------------------------------------------------------------------------------------------------
  # FRONT
  # --------------------------------------------------------------------------------------------------------------------

  admin-front-server:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/front
      dockerfile: build/server/Dockerfile
    environment:
      APP_NAME: ${DEPLOY_ADMIN_APP_NAME}
      BASE_URL: ${DEPLOY_ADMIN_BASE_URL}
      SESSION_COOKIE_NAME: ${ADMIN_FRONT_SESSION_COOKIE_NAME}
      API_BASEURL: "http://admin-gateway-http:80"
    develop:
      watch:
        - action: rebuild
          path: admin/front/app
        - action: rebuild
          path: admin/front/build/server

  # --------------------------------------------------------------------------------------------------------------------
  # GATEWAY
  # --------------------------------------------------------------------------------------------------------------------

  admin-gateway-http:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/gateway
      dockerfile: build/http/Dockerfile
    environment:
      REDIS_CACHE_HOST: ${INFRASTRUCTURE_REDIS_HOST_CACHE}
      REDIS_CACHE_USER: ${INFRASTRUCTURE_REDIS_CLIENT_APP_USER}
      REDIS_CACHE_PASSWORD: ${INFRASTRUCTURE_REDIS_CLIENT_APP_PASSWORD}
      REDIS_CACHE_DB: ${INFRASTRUCTURE_REDIS_DB_GATEWAY}
      SERVICE_AUTH_API_GRPC_BASEURL: "admin-auth-grpc:50051"
      SERVICE_AUTH_API_GRPC_APIKEY: ${ADMIN_AUTH_API_GRPC_APIKEY}
    volumes:
      - ./admin/gateway/state/http:/state
    develop:
      watch:
        - action: rebuild
          path: admin/gateway/app
        - action: rebuild
          path: admin/gateway/build/http

  # --------------------------------------------------------------------------------------------------------------------

  admin-gateway-kafcon:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/gateway
      dockerfile: build/kafcon/Dockerfile
    environment:
      KAFKA_BROKERS_HOSTPORTS: ${INFRASTRUCTURE_KAFKA_BROKERS_HOSTPORTS}
      # --
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_APP_PASSWORD}
      MYSQL_DB: ${INFRASTRUCTURE_MYSQL_DB_GATEWAY}
      # --
      REDIS_CACHE_HOST: ${INFRASTRUCTURE_REDIS_HOST_CACHE}
      REDIS_CACHE_USER: ${INFRASTRUCTURE_REDIS_CLIENT_APP_USER}
      REDIS_CACHE_PASSWORD: ${INFRASTRUCTURE_REDIS_CLIENT_APP_PASSWORD}
      REDIS_CACHE_DB: ${INFRASTRUCTURE_REDIS_DB_GATEWAY}
    volumes:
      - ./admin/gateway/state/kafcon:/state
    develop:
      watch:
        - action: rebuild
          path: admin/gateway/app
        - action: rebuild
          path: admin/gateway/build/kafcon

  # --------------------------------------------------------------------------------------------------------------------

  admin-gateway-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: admin/gateway
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./admin/gateway/state/logs-exporter:/state
      - ./admin/gateway/state/http:/input/http
      - ./admin/gateway/state/kafcon:/input/kafcon
    develop:
      watch:
        - action: rebuild
          path: admin/gateway/build/logs-exporter

  # --------------------------------------------------------------------------------------------------------------------
