name: example

# ----------------------------------------------------------------------------------------------------------------------
# СКРИПТЫ (см. также tools.sh)
# ----------------------------------------------------------------------------------------------------------------------
#
# Есть потребность в описании некоторых контейнеров, которые играют роль скриптов, а не сервисов.
# Хороший пример -- скрипт запуска миграций.
#
# Описание таких "одноразовых" контейнеров (тот же запуск миграций) рядом с "постоянными" (а это в основном сервера)
# может сбить с толку, т.к. визуального отличия в описании практически нет, а смысл совершенно разный.
# Также большое кол-во скриптов усложнит чтение и без того большого файла с описанием контейнеров приложений.
#
# Объявление же их вне compose-файлов заставляет дублировать части описания этих контейнеров (например, пути volume'ов),
# создавая дополнительные точки внесения изменений.
#
# Некоторые скрипты могут зависеть от запуска других сервисов. Директива "depends_on" решает эту проблему.
# Например, выполнение миграций не имеет смысла без успешного запуска контейнера с соответствующей базой данных.
#
# Использование WATCH в разработке также создает проблемы с запуском скриптов, запущенных вместе с сервисами приложений.
# При изменении наблюдаемых файлов в ЛЮБОМ сервисе ребилд перезапустит и уже остановленные контейнеры (те самые скрипты).
# Например, запуск недописанной миграции на беке из-за изменения в конфиге nginx на фронте -- это как минимум странно.
#
# Использование профилей в таких случаях не помогает, т.к. при наличии зависимостей от контейнеров из других профилей
# будет возникать ошибка о ненайденном контейнере.
# К тому же нужно прописывать профили для всех контейнеров, что чревато ошибками.
#
# ----------------
#
# Суть данного решения:
#   - описать скрипты-контейнеры, подчеркивая их отличие от контейнеров приложений: отдельный файл, именование
#   - исключить их из сценария развертывания (docker compose up): отдельный неиспользуемый профиль
#   - вызывать явно через "docker compose run --rm {container_name} [params]"
#
# Т.е. получаем все еще одну точку описания контейнеров (файлы docker-compose),
# но избавляемся от проблем смешивания разных типов контейнеров в описании и при развороте,
# а также получаем возможность их простого запуска как будто отдельных скриптов с сохранением зависимостей.
#
# ----------------------------------------------------------------------------------------------------------------------

x-prototypes:
  # Базовый прототип скрипта
  script-container: &script-container
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    profiles:
      - script-containers

  # Прототип скрипта управления миграциями - infrastructure-kafka
  migrate-infrastructure-kafka: &migrate-infrastructure-kafka
    <<: *script-container
    build:
      context: .migrator
    environment:
      KAFKA_BROKERS: ${INFRASTRUCTURE_KAFKA_BROKERS}
      KAFKA_CONNECT_BASE_URL: infrastructure-kafka-connect:8083
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_KAFKA_CONNECT_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_KAFKA_CONNECT_PASSWORD}
    volumes:
      - ./infrastructure/kafka/migrations:/migrations/scripts
      - ./infrastructure/kafka/state/migrations/state:/migrations/state
      - ./infrastructure/kafka/state/migrations/packages:/migrations/packages
    networks:
      - infrastructure-kafka-network
    depends_on:
      infrastructure-kafka-server-a:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-b:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-c:
        condition: service_healthy
        restart: false
      infrastructure-kafka-connect:
        condition: service_healthy
        restart: false
      infrastructure-mysql-master:
        condition: service_healthy

  # Прототип скрипта управления миграциями - infrastructure-mysql
  migrate-infrastructure-mysql: &migrate-infrastructure-mysql
    <<: *script-container
    build:
      context: .migrator
    environment:
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_MIGRATION_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_MIGRATION_PASSWORD}
      MYSQL_DB_AUTH: ${INFRASTRUCTURE_MYSQL_DB_AUTH}
      MYSQL_DB_CFM: ${INFRASTRUCTURE_MYSQL_DB_CFM}
    volumes:
      - ./infrastructure/mysql/migrations:/migrations/scripts
      - ./infrastructure/mysql/state/migrations/state:/migrations/state
      - ./infrastructure/mysql/state/migrations/packages:/migrations/packages
    depends_on:
      infrastructure-mysql-master:
        condition: service_healthy
        restart: false
    networks:
      - infrastructure-mysql-network

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Управление миграциями
  # --------------------------------------------------------------------------------------------------------------------

  # Infrastructure - Kafka
  script-migrate-infrastructure-kafka-new:
    <<: *migrate-infrastructure-kafka
    command: new
  script-migrate-infrastructure-kafka-up:
    <<: *migrate-infrastructure-kafka
    command: up
  script-migrate-infrastructure-kafka-down:
    <<: *migrate-infrastructure-kafka
    command: down

  # --------------------------------------------------------------------------------------------------------------------

  # Infrastructure - MySQL
  script-migrate-infrastructure-mysql-new:
    <<: *migrate-infrastructure-mysql
    command: new
  script-migrate-infrastructure-mysql-up:
    <<: *migrate-infrastructure-mysql
    command: up
  script-migrate-infrastructure-mysql-down:
    <<: *migrate-infrastructure-mysql
    command: down

  # --------------------------------------------------------------------------------------------------------------------
