name: example

services:
  # --------------------------------------------------------------------------------------------------------------------
  # KAFKA
  # https://docs.confluent.io/platform/current/installation/docker/config-reference.html
  # --------------------------------------------------------------------------------------------------------------------

  # Servers
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-kafka-server-a:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/kafka
      dockerfile: build/server/Dockerfile
      args:
        CLUSTER_ID: ${INFRASTRUCTURE_KAFKA_CLUSTER_ID}
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "101@infrastructure-kafka-server-a:9093,102@infrastructure-kafka-server-b:9093,103@infrastructure-kafka-server-c:9093"
      KAFKA_NODE_ID: 101
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://infrastructure-kafka-server-a:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - ./infrastructure/kafka/state/server-a/data:/var/lib/kafka/data
      - ./infrastructure/kafka/state/server-a/logs:/var/log/kafka/custom
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/server

  infrastructure-kafka-server-b:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/kafka
      dockerfile: build/server/Dockerfile
      args:
        CLUSTER_ID: ${INFRASTRUCTURE_KAFKA_CLUSTER_ID}
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "101@infrastructure-kafka-server-a:9093,102@infrastructure-kafka-server-b:9093,103@infrastructure-kafka-server-c:9093"
      KAFKA_NODE_ID: 102
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://infrastructure-kafka-server-b:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - ./infrastructure/kafka/state/server-b/data:/var/lib/kafka/data
      - ./infrastructure/kafka/state/server-b/logs:/var/log/kafka/custom
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/server

  infrastructure-kafka-server-c:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/kafka
      dockerfile: build/server/Dockerfile
      args:
        CLUSTER_ID: ${INFRASTRUCTURE_KAFKA_CLUSTER_ID}
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "101@infrastructure-kafka-server-a:9093,102@infrastructure-kafka-server-b:9093,103@infrastructure-kafka-server-c:9093"
      KAFKA_NODE_ID: 103
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://infrastructure-kafka-server-c:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
    volumes:
      - ./infrastructure/kafka/state/server-c/data:/var/lib/kafka/data
      - ./infrastructure/kafka/state/server-c/logs:/var/log/kafka/custom
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/server

  # Connect
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-kafka-connect:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/kafka
      dockerfile: build/connect/Dockerfile
    environment:
      MYSQL_HOST: infrastructure-mysql-master
      MYSQL_PORT: 3306
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_KAFKA_CONNECT_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_KAFKA_CONNECT_PASSWORD}
      CONNECT_REST_ADVERTISED_HOST_NAME: infrastructure-kafka-connect
      CONNECT_BOOTSTRAP_SERVERS: ${INFRASTRUCTURE_KAFKA_BROKERS}
    volumes:
      - ./infrastructure/kafka/state/connect/data:/var/lib/kafka/data
    depends_on:
      infrastructure-kafka-server-a:
        condition: service_healthy
      infrastructure-kafka-server-b:
        condition: service_healthy
      infrastructure-kafka-server-c:
        condition: service_healthy
      infrastructure-mysql-master:
        condition: service_healthy
      infrastructure-mysql-replica:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/connect

  # Logs
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-kafka-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/kafka
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./infrastructure/kafka/state/logs-exporter:/state
      - ./infrastructure/kafka/state/server-a/logs:/input/server-a
      - ./infrastructure/kafka/state/server-b/logs:/input/server-b
      - ./infrastructure/kafka/state/server-c/logs:/input/server-c
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/logs-exporter

  # Monitoring
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-kafka-prometheus-exporter:
    build:
      context: infrastructure/kafka
      dockerfile: build/prometheus-exporter/Dockerfile
    environment:
      BROKER_A: "infrastructure-kafka-server-a:9092"
      BROKER_B: "infrastructure-kafka-server-b:9092"
      BROKER_C: "infrastructure-kafka-server-c:9092"
    depends_on:
      # иначе экспортер не запускается из-за connection refused
      infrastructure-kafka-server-a:
        condition: service_healthy
      infrastructure-kafka-server-b:
        condition: service_healthy
      infrastructure-kafka-server-c:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: infrastructure/kafka/build/prometheus-exporter

  # --------------------------------------------------------------------------------------------------------------------
  # MYSQL
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-mysql-master:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/mysql
      dockerfile: build/server/Dockerfile
      args:
        INITIAL_ROOT_PASSWORD: "initial_root_password"
        SERVER_TYPE: master
        SERVER_ID: 1
    volumes:
      - ./infrastructure/mysql/state/server/master:/var/lib/mysql
    develop:
      watch:
        - action: rebuild
          path: infrastructure/mysql/build/server/master/custom.cnf
        - action: rebuild
          path: infrastructure/mysql/build/server/common.cnf
        - action: rebuild
          path: infrastructure/mysql/build/server/Dockerfile
        - action: rebuild
          path: infrastructure/mysql/build/server/healthcheck.sh

  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-mysql-replica:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/mysql
      dockerfile: build/server/Dockerfile
      args:
        INITIAL_ROOT_PASSWORD: "initial_root_password"
        SERVER_TYPE: replica
        SERVER_ID: 2
        EXTRA_REPLICA_SOURCE_HOST: "infrastructure-mysql-master"
    volumes:
      - ./infrastructure/mysql/state/server/replica:/var/lib/mysql
    develop:
      watch:
        - action: rebuild
          path: infrastructure/mysql/build/server/replica/custom.cnf
        - action: rebuild
          path: infrastructure/mysql/build/server/common.cnf
        - action: rebuild
          path: infrastructure/mysql/build/server/Dockerfile
        - action: rebuild
          path: infrastructure/mysql/build/server/healthcheck.sh

  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-mysql-prometheus-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/mysql
      dockerfile: build/prometheus-exporter/Dockerfile
      args:
        MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_PROMETHEUS_EXPORTER_USER}
        MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_PROMETHEUS_EXPORTER_PASSWORD}
    develop:
      watch:
        - action: rebuild
          path: infrastructure/mysql/build/prometheus-exporter

  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-mysql-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/mysql
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./infrastructure/mysql/state/logs-exporter:/state
      - ./infrastructure/mysql/state/server:/input
    develop:
      watch:
        - action: rebuild
          path: infrastructure/mysql/build/logs-exporter

  # --------------------------------------------------------------------------------------------------------------------
  # REDIS
  # --------------------------------------------------------------------------------------------------------------------

  infrastructure-redis-cache:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/redis
      dockerfile: build/server/Dockerfile
      args:
        SERVER_TYPE: cache
    volumes:
      - ./infrastructure/redis/state/server/cache:/data
    develop:
      watch:
        - action: rebuild
          path: infrastructure/redis/build/server/cache.conf
        - action: rebuild
          path: infrastructure/redis/build/server/Dockerfile
        - action: rebuild
          path: infrastructure/redis/build/server/*.sh

  infrastructure-redis-db:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/redis
      dockerfile: build/server/Dockerfile
      args:
        SERVER_TYPE: db
    volumes:
      - ./infrastructure/redis/state/server/db:/data
    develop:
      watch:
        - action: rebuild
          path: infrastructure/redis/build/server/db.conf
        - action: rebuild
          path: infrastructure/redis/build/server/Dockerfile
        - action: rebuild
          path: infrastructure/redis/build/server/*.sh

  infrastructure-redis-prometheus-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/redis
      dockerfile: build/prometheus-exporter/Dockerfile
    environment:
      REDIS_USER: ${INFRASTRUCTURE_REDIS_CLIENT_PROMETHEUS_EXPORTER_USER}
      REDIS_PASSWORD: ${INFRASTRUCTURE_REDIS_CLIENT_PROMETHEUS_EXPORTER_PASSWORD}
    depends_on:
      infrastructure-redis-cache:
        condition: service_healthy
      infrastructure-redis-db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: infrastructure/redis/build/prometheus-exporter

  infrastructure-redis-logs-exporter:
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    build:
      context: infrastructure/redis
      dockerfile: build/logs-exporter/Dockerfile
    volumes:
      - ./infrastructure/redis/state/logs-exporter:/state
      - ./infrastructure/redis/state/server:/input
    develop:
      watch:
        - action: rebuild
          path: infrastructure/redis/build/logs-exporter

  # --------------------------------------------------------------------------------------------------------------------
