name: example

# ----------------------------------------------------------------------------------------------------------------------
# СКРИПТЫ (см. также tools.sh)
# ----------------------------------------------------------------------------------------------------------------------
#
# Есть потребность в описании некоторых контейнеров, которые играют роль скриптов, а не сервисов.
# Хороший пример -- скрипт запуска миграций.
#
# Описание таких "одноразовых" контейнеров (тот же запуск миграций) рядом с "постоянными" (а это в основном сервера)
# может сбить с толку, т.к. визуального отличия в описании практически нет, а смысл совершенно разный.
# Также большое кол-во скриптов усложнит чтение и без того большого файла с описанием контейнеров приложений.
#
# Объявление же их вне compose-файлов заставляет дублировать части описания этих контейнеров (например, пути volume'ов),
# создавая дополнительные точки внесения изменений.
#
# Некоторые скрипты могут зависеть от запуска других сервисов. Директива "depends_on" решает эту проблему.
# Например, выполнение миграций не имеет смысла без успешного запуска контейнера с соответствующей базой данных.
#
# Использование WATCH в разработке также создает проблемы с запуском скриптов, запущенных вместе с сервисами приложений.
# При изменении наблюдаемых файлов в ЛЮБОМ сервисе ребилд перезапустит и уже остановленные контейнеры (те самые скрипты).
# Например, запуск недописанной миграции на беке из-за изменения в конфиге nginx на фронте -- это как минимум странно.
#
# Использование профилей в таких случаях не помогает, т.к. при наличии зависимостей от контейнеров из других профилей
# будет возникать ошибка о ненайденном контейнере.
# К тому же нужно прописывать профили для всех контейнеров, что чревато ошибками.
#
# ----------------
#
# Суть данного решения:
#   - описать скрипты-контейнеры, подчеркивая их отличие от контейнеров приложений: отдельный файл, именование
#   - исключить их из сценария развертывания (docker compose up): отдельный неиспользуемый профиль
#   - вызывать явно через "docker compose run --rm {container_name} [params]"
#
# Т.е. получаем все еще одну точку описания контейнеров (файлы docker-compose),
# но избавляемся от проблем смешивания разных типов контейнеров в описании и при развороте,
# а также получаем возможность их простого запуска как будто отдельных скриптов с сохранением зависимостей.
#
# ----------------------------------------------------------------------------------------------------------------------

x-prototypes:
  # Базовый прототип скрипта
  script-container: &script-container
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    profiles:
      - script-containers

  # Прототип скрипта управления миграциями
  migrate: &migrate
    <<: *script-container
    build:
      context: .migrator/build
    environment:
      KAFKA_BROKERS: ${INFRASTRUCTURE_KAFKA_BROKERS}
      KAFKA_CONNECT_BASE_URL: infrastructure-kafka-connect:8083
      MYSQL_HOST: ${INFRASTRUCTURE_MYSQL_HOST_MASTER}
      MYSQL_USER: ${INFRASTRUCTURE_MYSQL_CLIENT_MIGRATION_USER}
      MYSQL_PASSWORD: ${INFRASTRUCTURE_MYSQL_CLIENT_MIGRATION_PASSWORD}
      REDIS_HOST: ${INFRASTRUCTURE_REDIS_HOST_DB}
      REDIS_USER: ${INFRASTRUCTURE_REDIS_CLIENT_MIGRATION_USER}
      REDIS_PASSWORD: ${INFRASTRUCTURE_REDIS_CLIENT_MIGRATION_PASSWORD}
    volumes:
      - ./.migrator/scripts:/migrations/scripts
      - ./.migrator/state:/migrations/state

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Управление миграциями
  # --------------------------------------------------------------------------------------------------------------------

  script-migrate-new:
    <<: *migrate
    command: new

  script-migrate-up:
    <<: *migrate
    command: up
    networks:
      - infrastructure-kafka-network
      - infrastructure-mysql-network
      - infrastructure-redis-network
    depends_on:
      infrastructure-kafka-server-a:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-b:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-c:
        condition: service_healthy
        restart: false
      infrastructure-kafka-connect:
        condition: service_healthy
        restart: false
      infrastructure-mysql-master:
        condition: service_healthy
      infrastructure-redis-db:
        condition: service_healthy

  script-migrate-down:
    <<: *migrate
    command: down
    networks:
      - infrastructure-kafka-network
      - infrastructure-mysql-network
      - infrastructure-redis-network
    depends_on:
      infrastructure-kafka-server-a:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-b:
        condition: service_healthy
        restart: false
      infrastructure-kafka-server-c:
        condition: service_healthy
        restart: false
      infrastructure-kafka-connect:
        condition: service_healthy
        restart: false
      infrastructure-mysql-master:
        condition: service_healthy
      infrastructure-redis-db:
        condition: service_healthy

  # --------------------------------------------------------------------------------------------------------------------
