name: example

x-prototypes:
  # go
  dev-tools-go-general: &dev-tools-go-general
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    develop:
      watch:
        - action: rebuild
          path: ./go/
  dev-tools-go-build: &dev-tools-go-build
    context: ./go
    dockerfile: Dockerfile

# ----------------------------------------------------------------------------------------------------------------------

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Auth
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-admin-auth:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        GRPC_API_SERVICE_NAME: auth
    volumes:
      - ../../admin/auth/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Cfm
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-admin-cfm:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        GRPC_API_SERVICE_NAME: cfm
    volumes:
      - ../../admin/cfm/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Front
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-admin-front:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        GRPC_API_SERVICE_NAME: front
    volumes:
      - ../../admin/front/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - GATEWAY
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-admin-gateway:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        GRPC_API_SERVICE_NAME: gateway
    volumes:
      - ../../admin/gateway/app:/app

  # --------------------------------------------------------------------------------------------------------------------
