//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	SessIdScopes = "sessId.Scopes"
)

// PutAuthSignInConfirmJSONBody defines parameters for PutAuthSignInConfirm.
type PutAuthSignInConfirmJSONBody struct {
	Code     *string `json:"code,omitempty"`
	SignInId *string `json:"sign_in_id,omitempty"`
}

// PostAuthSignInRequestJSONBody defines parameters for PostAuthSignInRequest.
type PostAuthSignInRequestJSONBody struct {
	Email *string `json:"email,omitempty"`
}

// PutAuthSignInRequestRetryJSONBody defines parameters for PutAuthSignInRequestRetry.
type PutAuthSignInRequestRetryJSONBody struct {
	SignInId *string `json:"sign_in_id,omitempty"`
}

// PutAuthSignInConfirmJSONRequestBody defines body for PutAuthSignInConfirm for application/json ContentType.
type PutAuthSignInConfirmJSONRequestBody PutAuthSignInConfirmJSONBody

// PostAuthSignInRequestJSONRequestBody defines body for PostAuthSignInRequest for application/json ContentType.
type PostAuthSignInRequestJSONRequestBody PostAuthSignInRequestJSONBody

// PutAuthSignInRequestRetryJSONRequestBody defines body for PutAuthSignInRequestRetry for application/json ContentType.
type PutAuthSignInRequestRetryJSONRequestBody PutAuthSignInRequestRetryJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (PUT /auth/sign-in/confirm)
	PutAuthSignInConfirm(w http.ResponseWriter, r *http.Request)

	// (POST /auth/sign-in/request)
	PostAuthSignInRequest(w http.ResponseWriter, r *http.Request)

	// (PUT /auth/sign-in/request-retry)
	PutAuthSignInRequestRetry(w http.ResponseWriter, r *http.Request)

	// (DELETE /auth/sign-out)
	DeleteAuthSignOut(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PutAuthSignInConfirm operation middleware
func (siw *ServerInterfaceWrapper) PutAuthSignInConfirm(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessIdScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthSignInConfirm(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthSignInRequest operation middleware
func (siw *ServerInterfaceWrapper) PostAuthSignInRequest(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessIdScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthSignInRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAuthSignInRequestRetry operation middleware
func (siw *ServerInterfaceWrapper) PutAuthSignInRequestRetry(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessIdScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthSignInRequestRetry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAuthSignOut operation middleware
func (siw *ServerInterfaceWrapper) DeleteAuthSignOut(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessIdScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAuthSignOut(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("PUT "+options.BaseURL+"/auth/sign-in/confirm", wrapper.PutAuthSignInConfirm)
	m.HandleFunc("POST "+options.BaseURL+"/auth/sign-in/request", wrapper.PostAuthSignInRequest)
	m.HandleFunc("PUT "+options.BaseURL+"/auth/sign-in/request-retry", wrapper.PutAuthSignInRequestRetry)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/sign-out", wrapper.DeleteAuthSignOut)

	return m
}

type PutAuthSignInConfirmRequestObject struct {
	Body *PutAuthSignInConfirmJSONRequestBody
}

type PutAuthSignInConfirmResponseObject interface {
	VisitPutAuthSignInConfirmResponse(w http.ResponseWriter) error
}

type PutAuthSignInConfirm200JSONResponse struct {
	AttemptsLeft    *int    `json:"attempts_left,omitempty"`
	IsPassed        *bool   `json:"is_passed,omitempty"`
	SessionExpireAt *string `json:"session_expire_at,omitempty"`
	SessionId       *string `json:"session_id,omitempty"`
}

func (response PutAuthSignInConfirm200JSONResponse) VisitPutAuthSignInConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutAuthSignInConfirm422JSONResponse struct {
	// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PutAuthSignInConfirm422JSONResponse) VisitPutAuthSignInConfirmResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthSignInRequestRequestObject struct {
	Body *PostAuthSignInRequestJSONRequestBody
}

type PostAuthSignInRequestResponseObject interface {
	VisitPostAuthSignInRequestResponse(w http.ResponseWriter) error
}

type PostAuthSignInRequest200JSONResponse struct {
	CanRetryAt  *string `json:"can_retry_at,omitempty"`
	ExpireAt    *string `json:"expire_at,omitempty"`
	RetriesLeft *int    `json:"retries_left,omitempty"`
	SignInId    *string `json:"sign_in_id,omitempty"`
}

func (response PostAuthSignInRequest200JSONResponse) VisitPostAuthSignInRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostAuthSignInRequest422JSONResponse struct {
	// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PostAuthSignInRequest422JSONResponse) VisitPostAuthSignInRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PutAuthSignInRequestRetryRequestObject struct {
	Body *PutAuthSignInRequestRetryJSONRequestBody
}

type PutAuthSignInRequestRetryResponseObject interface {
	VisitPutAuthSignInRequestRetryResponse(w http.ResponseWriter) error
}

type PutAuthSignInRequestRetry200JSONResponse struct {
	CanRetryAt  *string `json:"can_retry_at,omitempty"`
	RetriesLeft *int    `json:"retries_left,omitempty"`
	SignInId    *string `json:"sign_in_id,omitempty"`
}

func (response PutAuthSignInRequestRetry200JSONResponse) VisitPutAuthSignInRequestRetryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutAuthSignInRequestRetry422JSONResponse struct {
	// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response PutAuthSignInRequestRetry422JSONResponse) VisitPutAuthSignInRequestRetryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAuthSignOutRequestObject struct {
}

type DeleteAuthSignOutResponseObject interface {
	VisitDeleteAuthSignOutResponse(w http.ResponseWriter) error
}

type DeleteAuthSignOut200JSONResponse struct {
	// Success всегда true -- костыль для OpenApi-генератора
	Success *bool `json:"success,omitempty"`
}

func (response DeleteAuthSignOut200JSONResponse) VisitDeleteAuthSignOutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAuthSignOut422JSONResponse struct {
	// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
	Code    int    `json:"code"`
	Message string `json:"message"`
}

func (response DeleteAuthSignOut422JSONResponse) VisitDeleteAuthSignOutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (PUT /auth/sign-in/confirm)
	PutAuthSignInConfirm(ctx context.Context, request PutAuthSignInConfirmRequestObject) (PutAuthSignInConfirmResponseObject, error)

	// (POST /auth/sign-in/request)
	PostAuthSignInRequest(ctx context.Context, request PostAuthSignInRequestRequestObject) (PostAuthSignInRequestResponseObject, error)

	// (PUT /auth/sign-in/request-retry)
	PutAuthSignInRequestRetry(ctx context.Context, request PutAuthSignInRequestRetryRequestObject) (PutAuthSignInRequestRetryResponseObject, error)

	// (DELETE /auth/sign-out)
	DeleteAuthSignOut(ctx context.Context, request DeleteAuthSignOutRequestObject) (DeleteAuthSignOutResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PutAuthSignInConfirm operation middleware
func (sh *strictHandler) PutAuthSignInConfirm(w http.ResponseWriter, r *http.Request) {
	var request PutAuthSignInConfirmRequestObject

	var body PutAuthSignInConfirmJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutAuthSignInConfirm(ctx, request.(PutAuthSignInConfirmRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAuthSignInConfirm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutAuthSignInConfirmResponseObject); ok {
		if err := validResponse.VisitPutAuthSignInConfirmResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostAuthSignInRequest operation middleware
func (sh *strictHandler) PostAuthSignInRequest(w http.ResponseWriter, r *http.Request) {
	var request PostAuthSignInRequestRequestObject

	var body PostAuthSignInRequestJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostAuthSignInRequest(ctx, request.(PostAuthSignInRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostAuthSignInRequest")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostAuthSignInRequestResponseObject); ok {
		if err := validResponse.VisitPostAuthSignInRequestResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutAuthSignInRequestRetry operation middleware
func (sh *strictHandler) PutAuthSignInRequestRetry(w http.ResponseWriter, r *http.Request) {
	var request PutAuthSignInRequestRetryRequestObject

	var body PutAuthSignInRequestRetryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutAuthSignInRequestRetry(ctx, request.(PutAuthSignInRequestRetryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutAuthSignInRequestRetry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutAuthSignInRequestRetryResponseObject); ok {
		if err := validResponse.VisitPutAuthSignInRequestRetryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAuthSignOut operation middleware
func (sh *strictHandler) DeleteAuthSignOut(w http.ResponseWriter, r *http.Request) {
	var request DeleteAuthSignOutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAuthSignOut(ctx, request.(DeleteAuthSignOutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAuthSignOut")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAuthSignOutResponseObject); ok {
		if err := validResponse.VisitDeleteAuthSignOutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
