// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_SignInRequest_FullMethodName      = "/admin_auth_v1.AuthService/SignInRequest"
	AuthService_SignInRequestRetry_FullMethodName = "/admin_auth_v1.AuthService/SignInRequestRetry"
	AuthService_SignInConfirm_FullMethodName      = "/admin_auth_v1.AuthService/SignInConfirm"
	AuthService_SignOut_FullMethodName            = "/admin_auth_v1.AuthService/SignOut"
	AuthService_CheckSession_FullMethodName       = "/admin_auth_v1.AuthService/CheckSession"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- аккаунт не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - INTERNAL
	SignInRequest(ctx context.Context, in *SignInRequestRequest, opts ...grpc.CallOption) (*SignInRequestResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- sign-in не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSignInFinishedDetail
	//   - ErrorNoAttemptsLeftDetail
	//   - ErrorRequestsFrequencyDetail
	//   - ErrorUnprocessableDetail -- сессия уже существует
	//   - INTERNAL
	SignInRequestRetry(ctx context.Context, in *SignInRequestRetryRequest, opts ...grpc.CallOption) (*SignInRequestRetryResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- sign-in не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSignInFinishedDetail
	//   - ErrorUnprocessableDetail -- сессия уже существует
	//   - INTERNAL
	SignInConfirm(ctx context.Context, in *SignInConfirmRequest, opts ...grpc.CallOption) (*SignInConfirmResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- сессия не найдена
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorAlreadyDoneDetail -- сессия уже закрыта
	//   - INTERNAL
	SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- сессия не найдена
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSessionClosedDetail
	//   - INTERNAL
	CheckSession(ctx context.Context, in *CheckSessionRequest, opts ...grpc.CallOption) (*CheckSessionResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignInRequest(ctx context.Context, in *SignInRequestRequest, opts ...grpc.CallOption) (*SignInRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInRequestResponse)
	err := c.cc.Invoke(ctx, AuthService_SignInRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignInRequestRetry(ctx context.Context, in *SignInRequestRetryRequest, opts ...grpc.CallOption) (*SignInRequestRetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInRequestRetryResponse)
	err := c.cc.Invoke(ctx, AuthService_SignInRequestRetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignInConfirm(ctx context.Context, in *SignInConfirmRequest, opts ...grpc.CallOption) (*SignInConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInConfirmResponse)
	err := c.cc.Invoke(ctx, AuthService_SignInConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignOut(ctx context.Context, in *SignOutRequest, opts ...grpc.CallOption) (*SignOutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignOutResponse)
	err := c.cc.Invoke(ctx, AuthService_SignOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckSession(ctx context.Context, in *CheckSessionRequest, opts ...grpc.CallOption) (*CheckSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSessionResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- аккаунт не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - INTERNAL
	SignInRequest(context.Context, *SignInRequestRequest) (*SignInRequestResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- sign-in не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSignInFinishedDetail
	//   - ErrorNoAttemptsLeftDetail
	//   - ErrorRequestsFrequencyDetail
	//   - ErrorUnprocessableDetail -- сессия уже существует
	//   - INTERNAL
	SignInRequestRetry(context.Context, *SignInRequestRetryRequest) (*SignInRequestRetryResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- sign-in не найден
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSignInFinishedDetail
	//   - ErrorUnprocessableDetail -- сессия уже существует
	//   - INTERNAL
	SignInConfirm(context.Context, *SignInConfirmRequest) (*SignInConfirmResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- сессия не найдена
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorAlreadyDoneDetail -- сессия уже закрыта
	//   - INTERNAL
	SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND -- сессия не найдена
	//   - FAILED_PRECONDITION:
	//   - ErrorValidationDetail
	//   - ErrorAccountAccessDeniedDetail
	//   - ErrorSessionClosedDetail
	//   - INTERNAL
	CheckSession(context.Context, *CheckSessionRequest) (*CheckSessionResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) SignInRequest(context.Context, *SignInRequestRequest) (*SignInRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInRequest not implemented")
}
func (UnimplementedAuthServiceServer) SignInRequestRetry(context.Context, *SignInRequestRetryRequest) (*SignInRequestRetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInRequestRetry not implemented")
}
func (UnimplementedAuthServiceServer) SignInConfirm(context.Context, *SignInConfirmRequest) (*SignInConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInConfirm not implemented")
}
func (UnimplementedAuthServiceServer) SignOut(context.Context, *SignOutRequest) (*SignOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOut not implemented")
}
func (UnimplementedAuthServiceServer) CheckSession(context.Context, *CheckSessionRequest) (*CheckSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSession not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_SignInRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignInRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignInRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignInRequest(ctx, req.(*SignInRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignInRequestRetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequestRetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignInRequestRetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignInRequestRetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignInRequestRetry(ctx, req.(*SignInRequestRetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignInConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignInConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignInConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignInConfirm(ctx, req.(*SignInConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SignOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignOut(ctx, req.(*SignOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckSession(ctx, req.(*CheckSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_auth_v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignInRequest",
			Handler:    _AuthService_SignInRequest_Handler,
		},
		{
			MethodName: "SignInRequestRetry",
			Handler:    _AuthService_SignInRequestRetry_Handler,
		},
		{
			MethodName: "SignInConfirm",
			Handler:    _AuthService_SignInConfirm_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _AuthService_SignOut_Handler,
		},
		{
			MethodName: "CheckSession",
			Handler:    _AuthService_CheckSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
