// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: cfm.cfm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorFinishedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfmId         string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	IsAsExpired   bool                   `protobuf:"varint,3,opt,name=isAsExpired,proto3" json:"isAsExpired,omitempty"`
	IsAsFailed    bool                   `protobuf:"varint,4,opt,name=isAsFailed,proto3" json:"isAsFailed,omitempty"`
	IsAsPassed    bool                   `protobuf:"varint,5,opt,name=isAsPassed,proto3" json:"isAsPassed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFinishedDetail) Reset() {
	*x = ErrorFinishedDetail{}
	mi := &file_cfm_cfm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFinishedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFinishedDetail) ProtoMessage() {}

func (x *ErrorFinishedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFinishedDetail.ProtoReflect.Descriptor instead.
func (*ErrorFinishedDetail) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorFinishedDetail) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *ErrorFinishedDetail) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ErrorFinishedDetail) GetIsAsExpired() bool {
	if x != nil {
		return x.IsAsExpired
	}
	return false
}

func (x *ErrorFinishedDetail) GetIsAsFailed() bool {
	if x != nil {
		return x.IsAsFailed
	}
	return false
}

func (x *ErrorFinishedDetail) GetIsAsPassed() bool {
	if x != nil {
		return x.IsAsPassed
	}
	return false
}

type ErrorNoAttemptsLeftDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfmId         string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorNoAttemptsLeftDetail) Reset() {
	*x = ErrorNoAttemptsLeftDetail{}
	mi := &file_cfm_cfm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorNoAttemptsLeftDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNoAttemptsLeftDetail) ProtoMessage() {}

func (x *ErrorNoAttemptsLeftDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNoAttemptsLeftDetail.ProtoReflect.Descriptor instead.
func (*ErrorNoAttemptsLeftDetail) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorNoAttemptsLeftDetail) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

type ErrorRequestsFrequencyDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CfmId              string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	CanReqAttemptsLeft uint32                 `protobuf:"varint,2,opt,name=canReqAttemptsLeft,proto3" json:"canReqAttemptsLeft,omitempty"`
	CanReqAfter        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=canReqAfter,proto3" json:"canReqAfter,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ErrorRequestsFrequencyDetail) Reset() {
	*x = ErrorRequestsFrequencyDetail{}
	mi := &file_cfm_cfm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRequestsFrequencyDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRequestsFrequencyDetail) ProtoMessage() {}

func (x *ErrorRequestsFrequencyDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRequestsFrequencyDetail.ProtoReflect.Descriptor instead.
func (*ErrorRequestsFrequencyDetail) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorRequestsFrequencyDetail) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *ErrorRequestsFrequencyDetail) GetCanReqAttemptsLeft() uint32 {
	if x != nil {
		return x.CanReqAttemptsLeft
	}
	return 0
}

func (x *ErrorRequestsFrequencyDetail) GetCanReqAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CanReqAfter
	}
	return nil
}

type ErrorNotRequestedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfmId         string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorNotRequestedDetail) Reset() {
	*x = ErrorNotRequestedDetail{}
	mi := &file_cfm_cfm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorNotRequestedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNotRequestedDetail) ProtoMessage() {}

func (x *ErrorNotRequestedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNotRequestedDetail.ProtoReflect.Descriptor instead.
func (*ErrorNotRequestedDetail) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorNotRequestedDetail) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

type CreateForEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForEmailRequest) Reset() {
	*x = CreateForEmailRequest{}
	mi := &file_cfm_cfm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForEmailRequest) ProtoMessage() {}

func (x *CreateForEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForEmailRequest.ProtoReflect.Descriptor instead.
func (*CreateForEmailRequest) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{4}
}

func (x *CreateForEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateForEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CfmId         string                 `protobuf:"bytes,2,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateForEmailResponse) Reset() {
	*x = CreateForEmailResponse{}
	mi := &file_cfm_cfm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateForEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateForEmailResponse) ProtoMessage() {}

func (x *CreateForEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateForEmailResponse.ProtoReflect.Descriptor instead.
func (*CreateForEmailResponse) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{5}
}

func (x *CreateForEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateForEmailResponse) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *CreateForEmailResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfmId         string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_cfm_cfm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{6}
}

func (x *RequestRequest) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

type RequestResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CfmId              string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	CanReqAgain        bool                   `protobuf:"varint,2,opt,name=canReqAgain,proto3" json:"canReqAgain,omitempty"`
	CanReqAttemptsLeft uint32                 `protobuf:"varint,3,opt,name=canReqAttemptsLeft,proto3" json:"canReqAttemptsLeft,omitempty"`
	CanReqAfter        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=canReqAfter,proto3" json:"canReqAfter,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_cfm_cfm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{7}
}

func (x *RequestResponse) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *RequestResponse) GetCanReqAgain() bool {
	if x != nil {
		return x.CanReqAgain
	}
	return false
}

func (x *RequestResponse) GetCanReqAttemptsLeft() uint32 {
	if x != nil {
		return x.CanReqAttemptsLeft
	}
	return 0
}

func (x *RequestResponse) GetCanReqAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CanReqAfter
	}
	return nil
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfmId         string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_cfm_cfm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmRequest) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *ConfirmRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ConfirmResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CfmId              string                 `protobuf:"bytes,1,opt,name=cfmId,proto3" json:"cfmId,omitempty"`
	FinishedAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	IsFinishedAsFailed bool                   `protobuf:"varint,3,opt,name=isFinishedAsFailed,proto3" json:"isFinishedAsFailed,omitempty"`
	IsFinishedAsPassed bool                   `protobuf:"varint,4,opt,name=isFinishedAsPassed,proto3" json:"isFinishedAsPassed,omitempty"`
	FailsLeft          uint32                 `protobuf:"varint,5,opt,name=failsLeft,proto3" json:"failsLeft,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_cfm_cfm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cfm_cfm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_cfm_cfm_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmResponse) GetCfmId() string {
	if x != nil {
		return x.CfmId
	}
	return ""
}

func (x *ConfirmResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ConfirmResponse) GetIsFinishedAsFailed() bool {
	if x != nil {
		return x.IsFinishedAsFailed
	}
	return false
}

func (x *ConfirmResponse) GetIsFinishedAsPassed() bool {
	if x != nil {
		return x.IsFinishedAsPassed
	}
	return false
}

func (x *ConfirmResponse) GetFailsLeft() uint32 {
	if x != nil {
		return x.FailsLeft
	}
	return 0
}

var File_cfm_cfm_proto protoreflect.FileDescriptor

const file_cfm_cfm_proto_rawDesc = "" +
	"\n" +
	"\rcfm.cfm.proto\x12\fadmin_cfm_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\x13ErrorFinishedDetail\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\x12:\n" +
	"\n" +
	"finishedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12 \n" +
	"\visAsExpired\x18\x03 \x01(\bR\visAsExpired\x12\x1e\n" +
	"\n" +
	"isAsFailed\x18\x04 \x01(\bR\n" +
	"isAsFailed\x12\x1e\n" +
	"\n" +
	"isAsPassed\x18\x05 \x01(\bR\n" +
	"isAsPassed\"1\n" +
	"\x19ErrorNoAttemptsLeftDetail\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\"\xa2\x01\n" +
	"\x1cErrorRequestsFrequencyDetail\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\x12.\n" +
	"\x12canReqAttemptsLeft\x18\x02 \x01(\rR\x12canReqAttemptsLeft\x12<\n" +
	"\vcanReqAfter\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcanReqAfter\"/\n" +
	"\x17ErrorNotRequestedDetail\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\"-\n" +
	"\x15CreateForEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"|\n" +
	"\x16CreateForEmailResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05cfmId\x18\x02 \x01(\tR\x05cfmId\x126\n" +
	"\bexpireAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"&\n" +
	"\x0eRequestRequest\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\"\xb7\x01\n" +
	"\x0fRequestResponse\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\x12 \n" +
	"\vcanReqAgain\x18\x02 \x01(\bR\vcanReqAgain\x12.\n" +
	"\x12canReqAttemptsLeft\x18\x03 \x01(\rR\x12canReqAttemptsLeft\x12<\n" +
	"\vcanReqAfter\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcanReqAfter\":\n" +
	"\x0eConfirmRequest\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xe1\x01\n" +
	"\x0fConfirmResponse\x12\x14\n" +
	"\x05cfmId\x18\x01 \x01(\tR\x05cfmId\x12:\n" +
	"\n" +
	"finishedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12.\n" +
	"\x12isFinishedAsFailed\x18\x03 \x01(\bR\x12isFinishedAsFailed\x12.\n" +
	"\x12isFinishedAsPassed\x18\x04 \x01(\bR\x12isFinishedAsPassed\x12\x1c\n" +
	"\tfailsLeft\x18\x05 \x01(\rR\tfailsLeft2\xf9\x01\n" +
	"\n" +
	"CfmService\x12[\n" +
	"\x0eCreateForEmail\x12#.admin_cfm_v1.CreateForEmailRequest\x1a$.admin_cfm_v1.CreateForEmailResponse\x12F\n" +
	"\aRequest\x12\x1c.admin_cfm_v1.RequestRequest\x1a\x1d.admin_cfm_v1.RequestResponse\x12F\n" +
	"\aConfirm\x12\x1c.admin_cfm_v1.ConfirmRequest\x1a\x1d.admin_cfm_v1.ConfirmResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_cfm_cfm_proto_rawDescOnce sync.Once
	file_cfm_cfm_proto_rawDescData []byte
)

func file_cfm_cfm_proto_rawDescGZIP() []byte {
	file_cfm_cfm_proto_rawDescOnce.Do(func() {
		file_cfm_cfm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cfm_cfm_proto_rawDesc), len(file_cfm_cfm_proto_rawDesc)))
	})
	return file_cfm_cfm_proto_rawDescData
}

var file_cfm_cfm_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cfm_cfm_proto_goTypes = []any{
	(*ErrorFinishedDetail)(nil),          // 0: admin_cfm_v1.ErrorFinishedDetail
	(*ErrorNoAttemptsLeftDetail)(nil),    // 1: admin_cfm_v1.ErrorNoAttemptsLeftDetail
	(*ErrorRequestsFrequencyDetail)(nil), // 2: admin_cfm_v1.ErrorRequestsFrequencyDetail
	(*ErrorNotRequestedDetail)(nil),      // 3: admin_cfm_v1.ErrorNotRequestedDetail
	(*CreateForEmailRequest)(nil),        // 4: admin_cfm_v1.CreateForEmailRequest
	(*CreateForEmailResponse)(nil),       // 5: admin_cfm_v1.CreateForEmailResponse
	(*RequestRequest)(nil),               // 6: admin_cfm_v1.RequestRequest
	(*RequestResponse)(nil),              // 7: admin_cfm_v1.RequestResponse
	(*ConfirmRequest)(nil),               // 8: admin_cfm_v1.ConfirmRequest
	(*ConfirmResponse)(nil),              // 9: admin_cfm_v1.ConfirmResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_cfm_cfm_proto_depIdxs = []int32{
	10, // 0: admin_cfm_v1.ErrorFinishedDetail.finishedAt:type_name -> google.protobuf.Timestamp
	10, // 1: admin_cfm_v1.ErrorRequestsFrequencyDetail.canReqAfter:type_name -> google.protobuf.Timestamp
	10, // 2: admin_cfm_v1.CreateForEmailResponse.expireAt:type_name -> google.protobuf.Timestamp
	10, // 3: admin_cfm_v1.RequestResponse.canReqAfter:type_name -> google.protobuf.Timestamp
	10, // 4: admin_cfm_v1.ConfirmResponse.finishedAt:type_name -> google.protobuf.Timestamp
	4,  // 5: admin_cfm_v1.CfmService.CreateForEmail:input_type -> admin_cfm_v1.CreateForEmailRequest
	6,  // 6: admin_cfm_v1.CfmService.Request:input_type -> admin_cfm_v1.RequestRequest
	8,  // 7: admin_cfm_v1.CfmService.Confirm:input_type -> admin_cfm_v1.ConfirmRequest
	5,  // 8: admin_cfm_v1.CfmService.CreateForEmail:output_type -> admin_cfm_v1.CreateForEmailResponse
	7,  // 9: admin_cfm_v1.CfmService.Request:output_type -> admin_cfm_v1.RequestResponse
	9,  // 10: admin_cfm_v1.CfmService.Confirm:output_type -> admin_cfm_v1.ConfirmResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cfm_cfm_proto_init() }
func file_cfm_cfm_proto_init() {
	if File_cfm_cfm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cfm_cfm_proto_rawDesc), len(file_cfm_cfm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cfm_cfm_proto_goTypes,
		DependencyIndexes: file_cfm_cfm_proto_depIdxs,
		MessageInfos:      file_cfm_cfm_proto_msgTypes,
	}.Build()
	File_cfm_cfm_proto = out.File
	file_cfm_cfm_proto_goTypes = nil
	file_cfm_cfm_proto_depIdxs = nil
}
