name: example

x-prototypes:
  dev-tools-go-general: &dev-tools-go-general
    user: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile

  dev-tools-go-build: &dev-tools-go-build
    context: ./
    dockerfile: Dockerfile

  dev-tools-go-build-args: &dev-tools-go-build-args
    USER: "${DEPLOY_CONTAINER_USER_UID}:${DEPLOY_CONTAINER_USER_GID}"

# ----------------------------------------------------------------------------------------------------------------------

# См. `tools.sh go {NAME}`

services:
  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Auth
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-go-admin-auth:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        << : *dev-tools-go-build-args
        SERVICE_NAME: auth
    volumes:
      - ../../../admin/auth/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Cfm
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-go-admin-cfm:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        << : *dev-tools-go-build-args
        SERVICE_NAME: cfm
    volumes:
      - ../../../admin/cfm/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Front
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-go-admin-front:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        << : *dev-tools-go-build-args
        SERVICE_NAME: front
    volumes:
      - ../../../admin/front/app:/app

  # --------------------------------------------------------------------------------------------------------------------
  # Admin - Gateway
  # --------------------------------------------------------------------------------------------------------------------

  dev-tools-go-admin-gateway:
    << : *dev-tools-go-general
    build:
      << : *dev-tools-go-build
      args:
        << : *dev-tools-go-build-args
        SERVICE_NAME: gateway
    volumes:
      - ../../../admin/gateway/app:/app

  # --------------------------------------------------------------------------------------------------------------------
