// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: auth.auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorValidationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorValidationDetail) Reset() {
	*x = ErrorValidationDetail{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorValidationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorValidationDetail) ProtoMessage() {}

func (x *ErrorValidationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorValidationDetail.ProtoReflect.Descriptor instead.
func (*ErrorValidationDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorValidationDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorValidationDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorAccountAccessDeniedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAccountAccessDeniedDetail) Reset() {
	*x = ErrorAccountAccessDeniedDetail{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAccountAccessDeniedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAccountAccessDeniedDetail) ProtoMessage() {}

func (x *ErrorAccountAccessDeniedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAccountAccessDeniedDetail.ProtoReflect.Descriptor instead.
func (*ErrorAccountAccessDeniedDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

type ErrorSignInFinishedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPassed      bool                   `protobuf:"varint,1,opt,name=isPassed,proto3" json:"isPassed,omitempty"`
	IsFailed      bool                   `protobuf:"varint,2,opt,name=isFailed,proto3" json:"isFailed,omitempty"`
	IsExpired     bool                   `protobuf:"varint,3,opt,name=isExpired,proto3" json:"isExpired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorSignInFinishedDetail) Reset() {
	*x = ErrorSignInFinishedDetail{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorSignInFinishedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorSignInFinishedDetail) ProtoMessage() {}

func (x *ErrorSignInFinishedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorSignInFinishedDetail.ProtoReflect.Descriptor instead.
func (*ErrorSignInFinishedDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorSignInFinishedDetail) GetIsPassed() bool {
	if x != nil {
		return x.IsPassed
	}
	return false
}

func (x *ErrorSignInFinishedDetail) GetIsFailed() bool {
	if x != nil {
		return x.IsFailed
	}
	return false
}

func (x *ErrorSignInFinishedDetail) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

type ErrorNoAttemptsLeftDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorNoAttemptsLeftDetail) Reset() {
	*x = ErrorNoAttemptsLeftDetail{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorNoAttemptsLeftDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNoAttemptsLeftDetail) ProtoMessage() {}

func (x *ErrorNoAttemptsLeftDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNoAttemptsLeftDetail.ProtoReflect.Descriptor instead.
func (*ErrorNoAttemptsLeftDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

type ErrorRequestsFrequencyDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CanReqAfter        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=canReqAfter,proto3" json:"canReqAfter,omitempty"`
	CanReqAttemptsLeft int32                  `protobuf:"varint,2,opt,name=canReqAttemptsLeft,proto3" json:"canReqAttemptsLeft,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ErrorRequestsFrequencyDetail) Reset() {
	*x = ErrorRequestsFrequencyDetail{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorRequestsFrequencyDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorRequestsFrequencyDetail) ProtoMessage() {}

func (x *ErrorRequestsFrequencyDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorRequestsFrequencyDetail.ProtoReflect.Descriptor instead.
func (*ErrorRequestsFrequencyDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorRequestsFrequencyDetail) GetCanReqAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CanReqAfter
	}
	return nil
}

func (x *ErrorRequestsFrequencyDetail) GetCanReqAttemptsLeft() int32 {
	if x != nil {
		return x.CanReqAttemptsLeft
	}
	return 0
}

type ErrorUnprocessableDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorUnprocessableDetail) Reset() {
	*x = ErrorUnprocessableDetail{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorUnprocessableDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorUnprocessableDetail) ProtoMessage() {}

func (x *ErrorUnprocessableDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorUnprocessableDetail.ProtoReflect.Descriptor instead.
func (*ErrorUnprocessableDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

type ErrorAlreadyDoneDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAlreadyDoneDetail) Reset() {
	*x = ErrorAlreadyDoneDetail{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAlreadyDoneDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAlreadyDoneDetail) ProtoMessage() {}

func (x *ErrorAlreadyDoneDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAlreadyDoneDetail.ProtoReflect.Descriptor instead.
func (*ErrorAlreadyDoneDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

type ErrorSessionClosedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExpired     bool                   `protobuf:"varint,1,opt,name=isExpired,proto3" json:"isExpired,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=closedAt,proto3" json:"closedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorSessionClosedDetail) Reset() {
	*x = ErrorSessionClosedDetail{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorSessionClosedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorSessionClosedDetail) ProtoMessage() {}

func (x *ErrorSessionClosedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorSessionClosedDetail.ProtoReflect.Descriptor instead.
func (*ErrorSessionClosedDetail) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorSessionClosedDetail) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

func (x *ErrorSessionClosedDetail) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type SignInRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIp        string                 `protobuf:"bytes,1,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	FromUserAgent string                 `protobuf:"bytes,2,opt,name=fromUserAgent,proto3" json:"fromUserAgent,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequestRequest) Reset() {
	*x = SignInRequestRequest{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequestRequest) ProtoMessage() {}

func (x *SignInRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequestRequest.ProtoReflect.Descriptor instead.
func (*SignInRequestRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *SignInRequestRequest) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *SignInRequestRequest) GetFromUserAgent() string {
	if x != nil {
		return x.FromUserAgent
	}
	return ""
}

func (x *SignInRequestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignInRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignInId      string                 `protobuf:"bytes,1,opt,name=signInId,proto3" json:"signInId,omitempty"`
	RetriesLeft   int32                  `protobuf:"varint,2,opt,name=retriesLeft,proto3" json:"retriesLeft,omitempty"`
	CanRetryAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=canRetryAt,proto3" json:"canRetryAt,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequestResponse) Reset() {
	*x = SignInRequestResponse{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequestResponse) ProtoMessage() {}

func (x *SignInRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequestResponse.ProtoReflect.Descriptor instead.
func (*SignInRequestResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *SignInRequestResponse) GetSignInId() string {
	if x != nil {
		return x.SignInId
	}
	return ""
}

func (x *SignInRequestResponse) GetRetriesLeft() int32 {
	if x != nil {
		return x.RetriesLeft
	}
	return 0
}

func (x *SignInRequestResponse) GetCanRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanRetryAt
	}
	return nil
}

func (x *SignInRequestResponse) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type SignInRequestRetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIp        string                 `protobuf:"bytes,1,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	FromUserAgent string                 `protobuf:"bytes,2,opt,name=fromUserAgent,proto3" json:"fromUserAgent,omitempty"`
	SignInId      string                 `protobuf:"bytes,3,opt,name=signInId,proto3" json:"signInId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequestRetryRequest) Reset() {
	*x = SignInRequestRetryRequest{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequestRetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequestRetryRequest) ProtoMessage() {}

func (x *SignInRequestRetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequestRetryRequest.ProtoReflect.Descriptor instead.
func (*SignInRequestRetryRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *SignInRequestRetryRequest) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *SignInRequestRetryRequest) GetFromUserAgent() string {
	if x != nil {
		return x.FromUserAgent
	}
	return ""
}

func (x *SignInRequestRetryRequest) GetSignInId() string {
	if x != nil {
		return x.SignInId
	}
	return ""
}

type SignInRequestRetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignInId      string                 `protobuf:"bytes,1,opt,name=signInId,proto3" json:"signInId,omitempty"`
	RetriesLeft   int32                  `protobuf:"varint,2,opt,name=retriesLeft,proto3" json:"retriesLeft,omitempty"`
	CanRetryAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=canRetryAt,proto3" json:"canRetryAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequestRetryResponse) Reset() {
	*x = SignInRequestRetryResponse{}
	mi := &file_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequestRetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequestRetryResponse) ProtoMessage() {}

func (x *SignInRequestRetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequestRetryResponse.ProtoReflect.Descriptor instead.
func (*SignInRequestRetryResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *SignInRequestRetryResponse) GetSignInId() string {
	if x != nil {
		return x.SignInId
	}
	return ""
}

func (x *SignInRequestRetryResponse) GetRetriesLeft() int32 {
	if x != nil {
		return x.RetriesLeft
	}
	return 0
}

func (x *SignInRequestRetryResponse) GetCanRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanRetryAt
	}
	return nil
}

type SignInConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIp        string                 `protobuf:"bytes,1,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	FromUserAgent string                 `protobuf:"bytes,2,opt,name=fromUserAgent,proto3" json:"fromUserAgent,omitempty"`
	SignInId      string                 `protobuf:"bytes,3,opt,name=signInId,proto3" json:"signInId,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInConfirmRequest) Reset() {
	*x = SignInConfirmRequest{}
	mi := &file_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInConfirmRequest) ProtoMessage() {}

func (x *SignInConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInConfirmRequest.ProtoReflect.Descriptor instead.
func (*SignInConfirmRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *SignInConfirmRequest) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *SignInConfirmRequest) GetFromUserAgent() string {
	if x != nil {
		return x.FromUserAgent
	}
	return ""
}

func (x *SignInConfirmRequest) GetSignInId() string {
	if x != nil {
		return x.SignInId
	}
	return ""
}

func (x *SignInConfirmRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SignInConfirmResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsPassed        bool                   `protobuf:"varint,1,opt,name=isPassed,proto3" json:"isPassed,omitempty"`
	AttemptsLeft    int32                  `protobuf:"varint,2,opt,name=attemptsLeft,proto3" json:"attemptsLeft,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	SessionExpireAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sessionExpireAt,proto3" json:"sessionExpireAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignInConfirmResponse) Reset() {
	*x = SignInConfirmResponse{}
	mi := &file_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInConfirmResponse) ProtoMessage() {}

func (x *SignInConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInConfirmResponse.ProtoReflect.Descriptor instead.
func (*SignInConfirmResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *SignInConfirmResponse) GetIsPassed() bool {
	if x != nil {
		return x.IsPassed
	}
	return false
}

func (x *SignInConfirmResponse) GetAttemptsLeft() int32 {
	if x != nil {
		return x.AttemptsLeft
	}
	return 0
}

func (x *SignInConfirmResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignInConfirmResponse) GetSessionExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionExpireAt
	}
	return nil
}

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIp        string                 `protobuf:"bytes,1,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	FromUserAgent string                 `protobuf:"bytes,2,opt,name=fromUserAgent,proto3" json:"fromUserAgent,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *SignOutRequest) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *SignOutRequest) GetFromUserAgent() string {
	if x != nil {
		return x.FromUserAgent
	}
	return ""
}

func (x *SignOutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SignOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutResponse) Reset() {
	*x = SignOutResponse{}
	mi := &file_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutResponse) ProtoMessage() {}

func (x *SignOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutResponse.ProtoReflect.Descriptor instead.
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{15}
}

type CheckSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIp        string                 `protobuf:"bytes,1,opt,name=fromIp,proto3" json:"fromIp,omitempty"`
	FromUserAgent string                 `protobuf:"bytes,2,opt,name=fromUserAgent,proto3" json:"fromUserAgent,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSessionRequest) Reset() {
	*x = CheckSessionRequest{}
	mi := &file_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSessionRequest) ProtoMessage() {}

func (x *CheckSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSessionRequest.ProtoReflect.Descriptor instead.
func (*CheckSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *CheckSessionRequest) GetFromIp() string {
	if x != nil {
		return x.FromIp
	}
	return ""
}

func (x *CheckSessionRequest) GetFromUserAgent() string {
	if x != nil {
		return x.FromUserAgent
	}
	return ""
}

func (x *CheckSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CheckSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	SessionExpireAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sessionExpireAt,proto3" json:"sessionExpireAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckSessionResponse) Reset() {
	*x = CheckSessionResponse{}
	mi := &file_auth_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSessionResponse) ProtoMessage() {}

func (x *CheckSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSessionResponse.ProtoReflect.Descriptor instead.
func (*CheckSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{17}
}

func (x *CheckSessionResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckSessionResponse) GetSessionExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionExpireAt
	}
	return nil
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth.auth.proto\x12\radmin_auth_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x15ErrorValidationDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x1eErrorAccountAccessDeniedDetail\"q\n" +
	"\x19ErrorSignInFinishedDetail\x12\x1a\n" +
	"\bisPassed\x18\x01 \x01(\bR\bisPassed\x12\x1a\n" +
	"\bisFailed\x18\x02 \x01(\bR\bisFailed\x12\x1c\n" +
	"\tisExpired\x18\x03 \x01(\bR\tisExpired\"\x1b\n" +
	"\x19ErrorNoAttemptsLeftDetail\"\x8c\x01\n" +
	"\x1cErrorRequestsFrequencyDetail\x12<\n" +
	"\vcanReqAfter\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vcanReqAfter\x12.\n" +
	"\x12canReqAttemptsLeft\x18\x02 \x01(\x05R\x12canReqAttemptsLeft\"\x1a\n" +
	"\x18ErrorUnprocessableDetail\"\x18\n" +
	"\x16ErrorAlreadyDoneDetail\"p\n" +
	"\x18ErrorSessionClosedDetail\x12\x1c\n" +
	"\tisExpired\x18\x01 \x01(\bR\tisExpired\x126\n" +
	"\bclosedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"j\n" +
	"\x14SignInRequestRequest\x12\x16\n" +
	"\x06fromIp\x18\x01 \x01(\tR\x06fromIp\x12$\n" +
	"\rfromUserAgent\x18\x02 \x01(\tR\rfromUserAgent\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xc9\x01\n" +
	"\x15SignInRequestResponse\x12\x1a\n" +
	"\bsignInId\x18\x01 \x01(\tR\bsignInId\x12 \n" +
	"\vretriesLeft\x18\x02 \x01(\x05R\vretriesLeft\x12:\n" +
	"\n" +
	"canRetryAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canRetryAt\x126\n" +
	"\bexpireAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"u\n" +
	"\x19SignInRequestRetryRequest\x12\x16\n" +
	"\x06fromIp\x18\x01 \x01(\tR\x06fromIp\x12$\n" +
	"\rfromUserAgent\x18\x02 \x01(\tR\rfromUserAgent\x12\x1a\n" +
	"\bsignInId\x18\x03 \x01(\tR\bsignInId\"\x96\x01\n" +
	"\x1aSignInRequestRetryResponse\x12\x1a\n" +
	"\bsignInId\x18\x01 \x01(\tR\bsignInId\x12 \n" +
	"\vretriesLeft\x18\x02 \x01(\x05R\vretriesLeft\x12:\n" +
	"\n" +
	"canRetryAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canRetryAt\"\x84\x01\n" +
	"\x14SignInConfirmRequest\x12\x16\n" +
	"\x06fromIp\x18\x01 \x01(\tR\x06fromIp\x12$\n" +
	"\rfromUserAgent\x18\x02 \x01(\tR\rfromUserAgent\x12\x1a\n" +
	"\bsignInId\x18\x03 \x01(\tR\bsignInId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\xbb\x01\n" +
	"\x15SignInConfirmResponse\x12\x1a\n" +
	"\bisPassed\x18\x01 \x01(\bR\bisPassed\x12\"\n" +
	"\fattemptsLeft\x18\x02 \x01(\x05R\fattemptsLeft\x12\x1c\n" +
	"\tsessionId\x18\x03 \x01(\tR\tsessionId\x12D\n" +
	"\x0fsessionExpireAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fsessionExpireAt\"l\n" +
	"\x0eSignOutRequest\x12\x16\n" +
	"\x06fromIp\x18\x01 \x01(\tR\x06fromIp\x12$\n" +
	"\rfromUserAgent\x18\x02 \x01(\tR\rfromUserAgent\x12\x1c\n" +
	"\tsessionId\x18\x03 \x01(\tR\tsessionId\"\x11\n" +
	"\x0fSignOutResponse\"q\n" +
	"\x13CheckSessionRequest\x12\x16\n" +
	"\x06fromIp\x18\x01 \x01(\tR\x06fromIp\x12$\n" +
	"\rfromUserAgent\x18\x02 \x01(\tR\rfromUserAgent\x12\x1c\n" +
	"\tsessionId\x18\x03 \x01(\tR\tsessionId\"z\n" +
	"\x14CheckSessionResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\x12D\n" +
	"\x0fsessionExpireAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fsessionExpireAt2\xd3\x03\n" +
	"\vAuthService\x12Z\n" +
	"\rSignInRequest\x12#.admin_auth_v1.SignInRequestRequest\x1a$.admin_auth_v1.SignInRequestResponse\x12i\n" +
	"\x12SignInRequestRetry\x12(.admin_auth_v1.SignInRequestRetryRequest\x1a).admin_auth_v1.SignInRequestRetryResponse\x12Z\n" +
	"\rSignInConfirm\x12#.admin_auth_v1.SignInConfirmRequest\x1a$.admin_auth_v1.SignInConfirmResponse\x12H\n" +
	"\aSignOut\x12\x1d.admin_auth_v1.SignOutRequest\x1a\x1e.admin_auth_v1.SignOutResponse\x12W\n" +
	"\fCheckSession\x12\".admin_auth_v1.CheckSessionRequest\x1a#.admin_auth_v1.CheckSessionResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_auth_auth_proto_goTypes = []any{
	(*ErrorValidationDetail)(nil),          // 0: admin_auth_v1.ErrorValidationDetail
	(*ErrorAccountAccessDeniedDetail)(nil), // 1: admin_auth_v1.ErrorAccountAccessDeniedDetail
	(*ErrorSignInFinishedDetail)(nil),      // 2: admin_auth_v1.ErrorSignInFinishedDetail
	(*ErrorNoAttemptsLeftDetail)(nil),      // 3: admin_auth_v1.ErrorNoAttemptsLeftDetail
	(*ErrorRequestsFrequencyDetail)(nil),   // 4: admin_auth_v1.ErrorRequestsFrequencyDetail
	(*ErrorUnprocessableDetail)(nil),       // 5: admin_auth_v1.ErrorUnprocessableDetail
	(*ErrorAlreadyDoneDetail)(nil),         // 6: admin_auth_v1.ErrorAlreadyDoneDetail
	(*ErrorSessionClosedDetail)(nil),       // 7: admin_auth_v1.ErrorSessionClosedDetail
	(*SignInRequestRequest)(nil),           // 8: admin_auth_v1.SignInRequestRequest
	(*SignInRequestResponse)(nil),          // 9: admin_auth_v1.SignInRequestResponse
	(*SignInRequestRetryRequest)(nil),      // 10: admin_auth_v1.SignInRequestRetryRequest
	(*SignInRequestRetryResponse)(nil),     // 11: admin_auth_v1.SignInRequestRetryResponse
	(*SignInConfirmRequest)(nil),           // 12: admin_auth_v1.SignInConfirmRequest
	(*SignInConfirmResponse)(nil),          // 13: admin_auth_v1.SignInConfirmResponse
	(*SignOutRequest)(nil),                 // 14: admin_auth_v1.SignOutRequest
	(*SignOutResponse)(nil),                // 15: admin_auth_v1.SignOutResponse
	(*CheckSessionRequest)(nil),            // 16: admin_auth_v1.CheckSessionRequest
	(*CheckSessionResponse)(nil),           // 17: admin_auth_v1.CheckSessionResponse
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
}
var file_auth_auth_proto_depIdxs = []int32{
	18, // 0: admin_auth_v1.ErrorRequestsFrequencyDetail.canReqAfter:type_name -> google.protobuf.Timestamp
	18, // 1: admin_auth_v1.ErrorSessionClosedDetail.closedAt:type_name -> google.protobuf.Timestamp
	18, // 2: admin_auth_v1.SignInRequestResponse.canRetryAt:type_name -> google.protobuf.Timestamp
	18, // 3: admin_auth_v1.SignInRequestResponse.expireAt:type_name -> google.protobuf.Timestamp
	18, // 4: admin_auth_v1.SignInRequestRetryResponse.canRetryAt:type_name -> google.protobuf.Timestamp
	18, // 5: admin_auth_v1.SignInConfirmResponse.sessionExpireAt:type_name -> google.protobuf.Timestamp
	18, // 6: admin_auth_v1.CheckSessionResponse.sessionExpireAt:type_name -> google.protobuf.Timestamp
	8,  // 7: admin_auth_v1.AuthService.SignInRequest:input_type -> admin_auth_v1.SignInRequestRequest
	10, // 8: admin_auth_v1.AuthService.SignInRequestRetry:input_type -> admin_auth_v1.SignInRequestRetryRequest
	12, // 9: admin_auth_v1.AuthService.SignInConfirm:input_type -> admin_auth_v1.SignInConfirmRequest
	14, // 10: admin_auth_v1.AuthService.SignOut:input_type -> admin_auth_v1.SignOutRequest
	16, // 11: admin_auth_v1.AuthService.CheckSession:input_type -> admin_auth_v1.CheckSessionRequest
	9,  // 12: admin_auth_v1.AuthService.SignInRequest:output_type -> admin_auth_v1.SignInRequestResponse
	11, // 13: admin_auth_v1.AuthService.SignInRequestRetry:output_type -> admin_auth_v1.SignInRequestRetryResponse
	13, // 14: admin_auth_v1.AuthService.SignInConfirm:output_type -> admin_auth_v1.SignInConfirmResponse
	15, // 15: admin_auth_v1.AuthService.SignOut:output_type -> admin_auth_v1.SignOutResponse
	17, // 16: admin_auth_v1.AuthService.CheckSession:output_type -> admin_auth_v1.CheckSessionResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
