// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: cfm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CfmService_CreateForEmail_FullMethodName = "/admin_cfm_v1.CfmService/CreateForEmail"
	CfmService_Request_FullMethodName        = "/admin_cfm_v1.CfmService/Request"
	CfmService_Confirm_FullMethodName        = "/admin_cfm_v1.CfmService/Confirm"
)

// CfmServiceClient is the client API for CfmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CfmServiceClient interface {
	// Errors:
	//   - INVALID_ARGUMENT
	//   - INTERNAL
	CreateForEmail(ctx context.Context, in *CreateForEmailRequest, opts ...grpc.CallOption) (*CreateForEmailResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND
	//   - FAILED_PRECONDITION:
	//   - ErrorFinishedDetail
	//   - ErrorNoAttemptsLeftDetail
	//   - ErrorRequestsFrequencyDetail
	//   - INTERNAL
	Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND
	//   - FAILED_PRECONDITION:
	//   - ErrorFinishedDetail
	//   - ErrorNotRequestedDetail
	//   - INTERNAL
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
}

type cfmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCfmServiceClient(cc grpc.ClientConnInterface) CfmServiceClient {
	return &cfmServiceClient{cc}
}

func (c *cfmServiceClient) CreateForEmail(ctx context.Context, in *CreateForEmailRequest, opts ...grpc.CallOption) (*CreateForEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateForEmailResponse)
	err := c.cc.Invoke(ctx, CfmService_CreateForEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cfmServiceClient) Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, CfmService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cfmServiceClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, CfmService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CfmServiceServer is the server API for CfmService service.
// All implementations must embed UnimplementedCfmServiceServer
// for forward compatibility.
type CfmServiceServer interface {
	// Errors:
	//   - INVALID_ARGUMENT
	//   - INTERNAL
	CreateForEmail(context.Context, *CreateForEmailRequest) (*CreateForEmailResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND
	//   - FAILED_PRECONDITION:
	//   - ErrorFinishedDetail
	//   - ErrorNoAttemptsLeftDetail
	//   - ErrorRequestsFrequencyDetail
	//   - INTERNAL
	Request(context.Context, *RequestRequest) (*RequestResponse, error)
	// Errors:
	//   - INVALID_ARGUMENT
	//   - NOT_FOUND
	//   - FAILED_PRECONDITION:
	//   - ErrorFinishedDetail
	//   - ErrorNotRequestedDetail
	//   - INTERNAL
	Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	mustEmbedUnimplementedCfmServiceServer()
}

// UnimplementedCfmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCfmServiceServer struct{}

func (UnimplementedCfmServiceServer) CreateForEmail(context.Context, *CreateForEmailRequest) (*CreateForEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateForEmail not implemented")
}
func (UnimplementedCfmServiceServer) Request(context.Context, *RequestRequest) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedCfmServiceServer) Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedCfmServiceServer) mustEmbedUnimplementedCfmServiceServer() {}
func (UnimplementedCfmServiceServer) testEmbeddedByValue()                    {}

// UnsafeCfmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CfmServiceServer will
// result in compilation errors.
type UnsafeCfmServiceServer interface {
	mustEmbedUnimplementedCfmServiceServer()
}

func RegisterCfmServiceServer(s grpc.ServiceRegistrar, srv CfmServiceServer) {
	// If the following call pancis, it indicates UnimplementedCfmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CfmService_ServiceDesc, srv)
}

func _CfmService_CreateForEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CfmServiceServer).CreateForEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CfmService_CreateForEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CfmServiceServer).CreateForEmail(ctx, req.(*CreateForEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CfmService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CfmServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CfmService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CfmServiceServer).Request(ctx, req.(*RequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CfmService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CfmServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CfmService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CfmServiceServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CfmService_ServiceDesc is the grpc.ServiceDesc for CfmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CfmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_cfm_v1.CfmService",
	HandlerType: (*CfmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateForEmail",
			Handler:    _CfmService_CreateForEmail_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _CfmService_Request_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _CfmService_Confirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cfm.proto",
}
