// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	SessIdScopes = "sessId.Scopes"
)

// PutAuthSignInConfirmJSONBody defines parameters for PutAuthSignInConfirm.
type PutAuthSignInConfirmJSONBody struct {
	Code     *string `json:"code,omitempty"`
	SignInId *string `json:"sign_in_id,omitempty"`
}

// PostAuthSignInRequestJSONBody defines parameters for PostAuthSignInRequest.
type PostAuthSignInRequestJSONBody struct {
	Email *string `json:"email,omitempty"`
}

// PutAuthSignInRequestRetryJSONBody defines parameters for PutAuthSignInRequestRetry.
type PutAuthSignInRequestRetryJSONBody struct {
	SignInId *string `json:"sign_in_id,omitempty"`
}

// PutAuthSignInConfirmJSONRequestBody defines body for PutAuthSignInConfirm for application/json ContentType.
type PutAuthSignInConfirmJSONRequestBody PutAuthSignInConfirmJSONBody

// PostAuthSignInRequestJSONRequestBody defines body for PostAuthSignInRequest for application/json ContentType.
type PostAuthSignInRequestJSONRequestBody PostAuthSignInRequestJSONBody

// PutAuthSignInRequestRetryJSONRequestBody defines body for PutAuthSignInRequestRetry for application/json ContentType.
type PutAuthSignInRequestRetryJSONRequestBody PutAuthSignInRequestRetryJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PutAuthSignInConfirmWithBody request with any body
	PutAuthSignInConfirmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutAuthSignInConfirm(ctx context.Context, body PutAuthSignInConfirmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAuthSignInRequestWithBody request with any body
	PostAuthSignInRequestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAuthSignInRequest(ctx context.Context, body PostAuthSignInRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutAuthSignInRequestRetryWithBody request with any body
	PutAuthSignInRequestRetryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutAuthSignInRequestRetry(ctx context.Context, body PutAuthSignInRequestRetryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAuthSignOut request
	DeleteAuthSignOut(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PutAuthSignInConfirmWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutAuthSignInConfirmRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutAuthSignInConfirm(ctx context.Context, body PutAuthSignInConfirmJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutAuthSignInConfirmRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthSignInRequestWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthSignInRequestRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthSignInRequest(ctx context.Context, body PostAuthSignInRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthSignInRequestRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutAuthSignInRequestRetryWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutAuthSignInRequestRetryRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutAuthSignInRequestRetry(ctx context.Context, body PutAuthSignInRequestRetryJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutAuthSignInRequestRetryRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAuthSignOut(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAuthSignOutRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPutAuthSignInConfirmRequest calls the generic PutAuthSignInConfirm builder with application/json body
func NewPutAuthSignInConfirmRequest(server string, body PutAuthSignInConfirmJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutAuthSignInConfirmRequestWithBody(server, "application/json", bodyReader)
}

// NewPutAuthSignInConfirmRequestWithBody generates requests for PutAuthSignInConfirm with any type of body
func NewPutAuthSignInConfirmRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/sign-in/confirm")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAuthSignInRequestRequest calls the generic PostAuthSignInRequest builder with application/json body
func NewPostAuthSignInRequestRequest(server string, body PostAuthSignInRequestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAuthSignInRequestRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAuthSignInRequestRequestWithBody generates requests for PostAuthSignInRequest with any type of body
func NewPostAuthSignInRequestRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/sign-in/request")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutAuthSignInRequestRetryRequest calls the generic PutAuthSignInRequestRetry builder with application/json body
func NewPutAuthSignInRequestRetryRequest(server string, body PutAuthSignInRequestRetryJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutAuthSignInRequestRetryRequestWithBody(server, "application/json", bodyReader)
}

// NewPutAuthSignInRequestRetryRequestWithBody generates requests for PutAuthSignInRequestRetry with any type of body
func NewPutAuthSignInRequestRetryRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/sign-in/request-retry")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAuthSignOutRequest generates requests for DeleteAuthSignOut
func NewDeleteAuthSignOutRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/sign-out")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PutAuthSignInConfirmWithBodyWithResponse request with any body
	PutAuthSignInConfirmWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAuthSignInConfirmResponse, error)

	PutAuthSignInConfirmWithResponse(ctx context.Context, body PutAuthSignInConfirmJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAuthSignInConfirmResponse, error)

	// PostAuthSignInRequestWithBodyWithResponse request with any body
	PostAuthSignInRequestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthSignInRequestResponse, error)

	PostAuthSignInRequestWithResponse(ctx context.Context, body PostAuthSignInRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthSignInRequestResponse, error)

	// PutAuthSignInRequestRetryWithBodyWithResponse request with any body
	PutAuthSignInRequestRetryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAuthSignInRequestRetryResponse, error)

	PutAuthSignInRequestRetryWithResponse(ctx context.Context, body PutAuthSignInRequestRetryJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAuthSignInRequestRetryResponse, error)

	// DeleteAuthSignOutWithResponse request
	DeleteAuthSignOutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAuthSignOutResponse, error)
}

type PutAuthSignInConfirmResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AttemptsLeft    *int    `json:"attempts_left,omitempty"`
		IsPassed        *bool   `json:"is_passed,omitempty"`
		SessionExpireAt *string `json:"session_expire_at,omitempty"`
		SessionId       *string `json:"session_id,omitempty"`
	}
	JSON422 *struct {
		// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
}

// Status returns HTTPResponse.Status
func (r PutAuthSignInConfirmResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutAuthSignInConfirmResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAuthSignInRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		CanRetryAt  *string `json:"can_retry_at,omitempty"`
		ExpireAt    *string `json:"expire_at,omitempty"`
		RetriesLeft *int    `json:"retries_left,omitempty"`
		SignInId    *string `json:"sign_in_id,omitempty"`
	}
	JSON422 *struct {
		// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
}

// Status returns HTTPResponse.Status
func (r PostAuthSignInRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAuthSignInRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutAuthSignInRequestRetryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		CanRetryAt  *string `json:"can_retry_at,omitempty"`
		RetriesLeft *int    `json:"retries_left,omitempty"`
		SignInId    *string `json:"sign_in_id,omitempty"`
	}
	JSON422 *struct {
		// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
}

// Status returns HTTPResponse.Status
func (r PutAuthSignInRequestRetryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutAuthSignInRequestRetryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAuthSignOutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Success всегда true -- костыль для OpenApi-генератора
		Success *bool `json:"success,omitempty"`
	}
	JSON422 *struct {
		// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
}

// Status returns HTTPResponse.Status
func (r DeleteAuthSignOutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAuthSignOutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PutAuthSignInConfirmWithBodyWithResponse request with arbitrary body returning *PutAuthSignInConfirmResponse
func (c *ClientWithResponses) PutAuthSignInConfirmWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAuthSignInConfirmResponse, error) {
	rsp, err := c.PutAuthSignInConfirmWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutAuthSignInConfirmResponse(rsp)
}

func (c *ClientWithResponses) PutAuthSignInConfirmWithResponse(ctx context.Context, body PutAuthSignInConfirmJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAuthSignInConfirmResponse, error) {
	rsp, err := c.PutAuthSignInConfirm(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutAuthSignInConfirmResponse(rsp)
}

// PostAuthSignInRequestWithBodyWithResponse request with arbitrary body returning *PostAuthSignInRequestResponse
func (c *ClientWithResponses) PostAuthSignInRequestWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthSignInRequestResponse, error) {
	rsp, err := c.PostAuthSignInRequestWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthSignInRequestResponse(rsp)
}

func (c *ClientWithResponses) PostAuthSignInRequestWithResponse(ctx context.Context, body PostAuthSignInRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthSignInRequestResponse, error) {
	rsp, err := c.PostAuthSignInRequest(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthSignInRequestResponse(rsp)
}

// PutAuthSignInRequestRetryWithBodyWithResponse request with arbitrary body returning *PutAuthSignInRequestRetryResponse
func (c *ClientWithResponses) PutAuthSignInRequestRetryWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutAuthSignInRequestRetryResponse, error) {
	rsp, err := c.PutAuthSignInRequestRetryWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutAuthSignInRequestRetryResponse(rsp)
}

func (c *ClientWithResponses) PutAuthSignInRequestRetryWithResponse(ctx context.Context, body PutAuthSignInRequestRetryJSONRequestBody, reqEditors ...RequestEditorFn) (*PutAuthSignInRequestRetryResponse, error) {
	rsp, err := c.PutAuthSignInRequestRetry(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutAuthSignInRequestRetryResponse(rsp)
}

// DeleteAuthSignOutWithResponse request returning *DeleteAuthSignOutResponse
func (c *ClientWithResponses) DeleteAuthSignOutWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DeleteAuthSignOutResponse, error) {
	rsp, err := c.DeleteAuthSignOut(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAuthSignOutResponse(rsp)
}

// ParsePutAuthSignInConfirmResponse parses an HTTP response from a PutAuthSignInConfirmWithResponse call
func ParsePutAuthSignInConfirmResponse(rsp *http.Response) (*PutAuthSignInConfirmResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutAuthSignInConfirmResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			AttemptsLeft    *int    `json:"attempts_left,omitempty"`
			IsPassed        *bool   `json:"is_passed,omitempty"`
			SessionExpireAt *string `json:"session_expire_at,omitempty"`
			SessionId       *string `json:"session_id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
			Code    int    `json:"code"`
			Message string `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePostAuthSignInRequestResponse parses an HTTP response from a PostAuthSignInRequestWithResponse call
func ParsePostAuthSignInRequestResponse(rsp *http.Response) (*PostAuthSignInRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAuthSignInRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CanRetryAt  *string `json:"can_retry_at,omitempty"`
			ExpireAt    *string `json:"expire_at,omitempty"`
			RetriesLeft *int    `json:"retries_left,omitempty"`
			SignInId    *string `json:"sign_in_id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
			Code    int    `json:"code"`
			Message string `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePutAuthSignInRequestRetryResponse parses an HTTP response from a PutAuthSignInRequestRetryWithResponse call
func ParsePutAuthSignInRequestRetryResponse(rsp *http.Response) (*PutAuthSignInRequestRetryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutAuthSignInRequestRetryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			CanRetryAt  *string `json:"can_retry_at,omitempty"`
			RetriesLeft *int    `json:"retries_left,omitempty"`
			SignInId    *string `json:"sign_in_id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
			Code    int    `json:"code"`
			Message string `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseDeleteAuthSignOutResponse parses an HTTP response from a DeleteAuthSignOutWithResponse call
func ParseDeleteAuthSignOutResponse(rsp *http.Response) (*DeleteAuthSignOutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAuthSignOutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Success всегда true -- костыль для OpenApi-генератора
			Success *bool `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			// Code 400 - ошибка валидации, 401 - требуется аутентификация, 403 - отказ в доступе, 404 - не найдено, 422 - специфическая ошибка ("заказ отменен" и т.д.)
			Code    int    `json:"code"`
			Message string `json:"message"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
